### ISSUE TITLE
Generic first/third party regex

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/pagexray#66]
I think we could change the current impl so that if do not apply a regex, we could use something like https://discuss.httparchive.org/t/analyzing-3rd-party-performance-via-http-archive-crux/1359 to determine how many 1st/3rd party we have.

**Comment by arunthilak** [comment]
Coach allows multiple domains for the 1st party as seen from the documentation. 
webcoach https://en.wikipedia.org/wiki/Barack_Obama --firstParty "(.*wikipedia.*||.*wikimedia.*)" 
Will that be possible with this enhancement for PageXray?

**Comment by soulgalore** [comment]
Yes it is already there. You can pass on --firstParty and it will work. The generic one is already implemented and kicks in only if there is no configured firstParty.

**Comment by arunthilak** [comment]
Thank you for the quick response @soulgalore .. For some reason, it doesnt work for me, I get "NA" in the third party section of the pagexray in the html report.. The html report works if I use a single domain, but even then it that still doesnt write to graphite for some reason.. So my 1st party vs 3rd party dashboard isn't working... I noticed your example 1st party vs 3rd party dashboard 
https://dashboard.sitespeed.io/d/000000048/3rd-vs-1st-party?refresh=15m&orgId=1

Would you be able to share the shell script or config file which generates the data for that dashboard? Might be helpful if I am not passing the arguments properly across sitespeed.io and it's plugins properly.. 

Many Thanks,
Arun Thilak

**Comment by soulgalore** [comment]
Hi @arunthilak ok, for Ryan Air on the dashboard I'm using `--firstParty ".ryanair.com"`. Is it possible for you to share how you run? I can look at it tonight, but in the making of sitespeed.io 8.0 the coming week so the code that runs on dashboard.sitespeed.io is the new code, so it could be that it is a bug in the old version.
Best
Peter

**Comment by arunthilak** [comment]
Thank you Peter, 
I have a Docker compose file based off of documentation on this page - https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/ 
docker-compose run sitespeed.io $PLUGINS $CABLE --firstParty "(.xyz.com||.ycom.cloud)" $url
where, 
PLUGINS="--plugins.remove webpagetest --plugins.remove tracestorer --gzipHAR"
CABLE="--config desktop.config.json"
and in the config file I only have configs for graphite and browsertime. None for Xray. 

I had tried multiple permutations: 
--firstParty "(.xyz.com||.ycom.cloud)" 
--firstParty "(.*.xyz.com.*||.*.ycom.cloud.*)" 
--firstParty ".xyz.com||.ycom.cloud" 


The following two items work consistently 
--firstParty "(.xyz.com)"
--firstParty "(.*.xyz.com)"
--firstParty ".xyz.com" 

Versions that I am using: [2019-01-20 04:57:50] INFO: [sitespeedio] Versions OS: linux 4.14.88-72.73.amzn1.x86_64 nodejs: v10.13.0 sitespeed.io: 7.7.3 browsertime: 3.11.1 coach: 2.4.0

**Comment by arunthilak** [comment]
Hi Peter, 
FYI - I pulled the latest version and I am still got the issue .. 


Many Thanks,
Arun Thilak

**Comment by soulgalore** [comment]
Can you share URL so I can test?

I've tested with `--firstParty "(en.wikipedia.org||upload.wikipedia.org)" https://en.wikipedia.org/wiki/Main_Page` and works.

It's a standard JavaScript RegEx so you should be able to try it out on https://regexr.com

Best
Peter

**Comment by arunthilak** [comment]
Hi Peter, 
I tested with nytimes.com. I dont believe it's the URL issue, I think there is something else wrong either with my environment (really shouldn't be a problem with Dockers) or I am doing something wrong ..  

I tried to run this without the docker-compose of any of the config files as I have mentioned above ... 
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.0.4 --firstParty "nytimes.com||nyt.com" -n 1 "https://www.nytimes.com"
` 
and here is the output on PageXray .. 
![image](https://user-images.githubusercontent.com/15929991/51776767-8f39f900-20c8-11e9-841a-3179509a9eaf.png)

Also, the math doesnt add up for the number of requests in the 1st party section to some other sections .. for the same test run as above - here is requests by type ... 
![image](https://user-images.githubusercontent.com/15929991/51776859-ef309f80-20c8-11e9-97cc-62556b729784.png)

**Comment by soulgalore** [comment]
Ok let me have a look tonight.

**Comment by arunthilak** [comment]
Hi Peter, 
Thank you, the single pipe seemed to have worked. And no, the difference I think I noticed is for the same run (iteration =1). Let me review the html report for the last run and let you know .. 


Many Thanks,
Arun Thilak

**Comment by soulgalore** [comment]
I think NYT will send you different ads different times, so you will always get different amount of 3rd parties.

**Comment by arunthilak** [comment]
Hi Soulgalore, 
Apologies for the delay in responding... I did go over this again, to make sure that I am looking at this right way - And again, apologies, I still don't get when you say, nytimes sends different ads at different times could be a root cause for the numbers not being accurate during the calculation of 1st party and 3rd party. Isn't pagexray working on a har file after a run is completed? Isn't that a static file?

Regardless, here is another page which I ran sitespeed on and found the calculations inaccurate in the 1st party/3rd party section. "https://www.accenture.com/us-en/new-applied-now" 
 
Below is the list of the requests by domain: ( -- firstParty .accenture.com )

Domain | Header Size | Transfer Size | Content Size | Requests
www.accenture.com | N/A | 892.4 KB | 2.3 MB | 21
cdn.cookielaw.org | N/A | 30.7 KB | 150.5 KB | 3
scripts.demandbase.com | N/A | 2.2 KB | 4.7 KB | 1
s.delvenetworks.com | 473 B | 18.3 KB | 18.3 KB | 1
assets.adobedtm.com | 5.8 KB | 193.8 KB | 754.0 KB | 14
dpm.demdex.net | 1.7 KB | 1016 B | 608 B | 3
code.jquery.com | 491 B | 29.6 KB | 84.9 KB | 1
somni.accenture.com | 1.3 KB | 415 B | 415 B | 2
cm.everesttech.net | 319 B | 208 B | 0 b | 1
geolocation.onetrust.com | 163 B | 33 B | 33 B | 1
api.demandbase.com | 1.5 KB | 544 B | 914 B | 2
www.google-analytics.com | N/A | 17.4 KB | 43.1 KB | 2
accenture.demdex.net | 565 B | 0 b | 0 b | 1
accenture.tt.omtrdc.net | N/A | 1.8 KB | 2.7 KB | 2
stats.g.doubleclick.net | N/A | N/A | 0 b | 1
www.google.com | N/A | 383 B | 42 B | 1
static.ads-twitter.com | N/A | 2.2 KB | 5.0 KB | 1
connect.facebook.net | N/A | 61.1 KB | 237.8 KB | 2
snap.licdn.com | 314 B | 4.5 KB | 14.9 KB | 1
js.hs-analytics.net | N/A | 24.7 KB | 71.8 KB | 1
www.googletagmanager.com | N/A | 23.5 KB | 61.2 KB | 1
d8rk54i4mohrb.cloudfront.net | N/A | 17.0 KB | 16.6 KB | 2
www.youtube.com | N/A | 1.1 KB | 859 B | 1
s.ytimg.com | N/A | 7.8 KB | 20.3 KB | 1
t.co | N/A | 486 B | 43 B | 1
edge.simplereach.com | 318 B | 165 B | 165 B | 2
8140983.fls.doubleclick.net | N/A | N/A | 0 b | 2
www.facebook.com | N/A | 293 B | 44 B | 2
px.ads.linkedin.com | N/A | 109 B | 0 b | 3
js.hs-scripts.com | N/A | 924 B | 860 B | 1
track.hubspot.com | N/A | 447 B | 45 B | 1
analytics.twitter.com | N/A | 671 B | 31 B | 1
www.linkedin.com | N/A | N/A | 0 b | 1
js.hsleadflows.net | N/A | 60.4 KB | 369.8 KB | 1
forms.hubspot.com | N/A | 4.0 KB | 26.5 KB | 1

From this list above, total First party requests should be 23 and the remaining should be 3rd party. But, here is what I find in the 1st party section; says the total as 40 and even in that same table, the last column adds up to only 34, not 40: 
![image](https://user-images.githubusercontent.com/15929991/53704290-76201880-3de9-11e9-970d-5b6bd78abe50.png)


Attaching the har file for your reference... 
[www.accenture.com_us-en_new-applied-now-chrome-2019-03-04000137.har.gz](https://github.com/sitespeedio/pagexray/files/2923879/www.accenture.com_us-en_new-applied-now-chrome-2019-03-04000137.har.gz)

**Comment by soulgalore** [comment]
Hi @arunthilak it doesn't match from the start by default so it matches full URLs so for example https://8140983.fls.doubleclick.net/activityi;dc_pre=CISb9rCX5-ACFUa-swodb8wBzw;src=8140983;type=usapl0;cat=fl_ac0;ord=2296346644803;gtm=2od241;auiddc=1890495089.1551657701;u1=https%3A%2F%2Fwww.accenture.com%2Fus-en;~oref=https%3A%2F%2Fwww.accenture.com%2Fus-en? is a match.

Best
Peter

**Comment by soulgalore** [comment]
Fixed that in 2.5.4.

**Comment by arunthilak** [comment]
@soulgalore 
Many Thanks Peter! Appreciate your quick turnaround!
